SEED_GUIDES = [
    {
        "category": "flood",
        "label": "Flood",
        "icon": "droplet",
        "before": ["Know your flood risk and evacuation route.", "Pack an emergency kit with water, food, torch, and documents.", "Elevate valuables and electrical fittings where possible."],
        "during": ["Move to higher ground immediately.", "Avoid walking or driving through moving water.", "Switch off mains power if safe to do so."],
        "after": ["Avoid floodwater — it may be contaminated.", "Check your home for structural damage before re-entering.", "Discard food that contacted floodwater."],
    },
    {
        "category": "fire",
        "label": "Fire",
        "icon": "flame",
        "before": ["Plan two exit routes from every room.", "Install and test smoke alarms monthly.", "Agree on a family meeting point outside."],
        "during": ["Get low under smoke and crawl to the exit.", "Feel doors before opening; use an alternate route if hot.", "Never use elevators during a fire."],
        "after": ["Do not re-enter the building until cleared by fire services.", "Watch for structural damage and hot spots.", "Contact your insurer and document damage."],
    },
    {
        "category": "earthquake",
        "label": "Earthquake",
        "icon": "activity",
        "before": ["Secure heavy furniture and shelving to walls.", "Identify safe spots under sturdy furniture in each room.", "Keep a flashlight and sturdy shoes near your bed."],
        "during": ["Drop, Cover, and Hold On until shaking stops.", "Stay away from windows and tall furniture.", "If outdoors, move away from buildings and power lines."],
        "after": ["Check for gas leaks and damaged wiring before using switches.", "Expect aftershocks and stay alert.", "Check on neighbors, especially elderly or disabled."],
    },
    {
        "category": "cyclone",
        "label": "Cyclone",
        "icon": "wind",
        "before": ["Track official cyclone bulletins for landfall time.", "Secure or bring in loose outdoor objects.", "Stock water, food, and batteries for several days."],
        "during": ["Stay indoors in the most interior, wind-protected room.", "Keep away from windows and glass doors.", "Avoid using landline phones during lightning."],
        "after": ["Watch for flash flooding even after winds calm.", "Avoid downed power lines and damaged structures.", "Boil drinking water until authorities confirm it's safe."],
    },
    {
        "category": "heatwave",
        "label": "Heatwave",
        "icon": "sun",
        "before": ["Check forecasts and plan outdoor tasks for cooler hours.", "Ensure fans/coolers are in working order.", "Identify a cool public space nearby as backup."],
        "during": ["Avoid outdoor activity between 12 PM and 4 PM.", "Drink water regularly, even without thirst.", "Wear light, loose, light-colored clothing."],
        "after": ["Watch for delayed heat-exhaustion symptoms.", "Rehydrate gradually and rest in a cool space.", "Check on vulnerable neighbors and relatives."],
    },
    {
        "category": "landslide",
        "label": "Landslide",
        "icon": "mountain",
        "before": ["Learn if your area has a landslide history.", "Watch for new ground cracks or tilting trees after heavy rain.", "Plan an evacuation route away from steep slopes."],
        "during": ["Move away from the slide's path, not downhill in front of it.", "Listen for unusual sounds like cracking trees or rumbling.", "Alert neighbors if you notice ground movement."],
        "after": ["Stay away from the slide area — further movement is possible.", "Report blocked or damaged roads to authorities.", "Check for damaged utility lines before entering structures."],
    },
]
